#!/usr/bin/env bash
# Generate linked_libs.md next to the built getdp.exe: what must ship with the
# binary, and what is already inside it. Called by build.sh after a successful
# build, so the list reflects the features this build actually enabled rather
# than a hand-maintained guess.
#
#   gen_linked_libs.sh [build-dir]
#
# build-dir defaults to $BUILDDIR, then to "build". ROOT defaults to the src/
# directory next to this script, so the script also runs standalone:
#
#   MKL=$C/Library PY=$C ./scripts/gen_linked_libs.sh build
#
# The remaining inputs describe what the build linked against, and should match
# the ones build.sh was run with:
#   MKL                           oneMKL prefix, for the version
#   PY, PYLIB                     embedded Python, if any
#   CUDSS_DIR, CUDA_TOOLKIT_DIR   GPU direct solve, if any
set -e
ROOT=${ROOT:-$(cd "$(dirname "$0")/../src" 2>/dev/null && pwd)}
[ -n "$ROOT" ] || { echo "$0: cannot locate src/ - set ROOT" >&2; exit 1; }
BUILDDIR=${1:-${BUILDDIR:-build}}
BDIR="$ROOT/cenos-getdp-fork/$BUILDDIR"
[ -d "$BDIR" ] || { echo "$0: no build directory $BDIR" >&2
                       echo "  pass the build dir as the first argument, e.g. $0 build" >&2; exit 1; }
OUT="$BDIR/linked_libs.md"
EXE="$BDIR/getdp.exe"

# --- facts about this build -------------------------------------------------

VERSION=$(sed -n 's/^#define GETDP_VERSION  *"\(.*\)"/\1/p' \
          "$BDIR/src/common/GetDPVersion.h" 2>/dev/null || true)
VERSION=${VERSION:-unknown}

MKLVER=""
if [ -f "$MKL/include/mkl_version.h" ]; then
  m=$(sed -n 's/^#define __INTEL_MKL__  *\([0-9]*\).*/\1/p'       "$MKL/include/mkl_version.h")
  n=$(sed -n 's/^#define __INTEL_MKL_MINOR__  *\([0-9]*\).*/\1/p' "$MKL/include/mkl_version.h")
  u=$(sed -n 's/^#define __INTEL_MKL_UPDATE__  *\([0-9]*\).*/\1/p' "$MKL/include/mkl_version.h")
  [ -n "$m" ] && MKLVER=" $m.$n.$u"
fi

PYDLL=""
if [ -n "${PY:-}" ]; then
  PYDLL=${PYLIB:-python310.lib}; PYDLL="${PYDLL%.lib}.dll"
fi

CUDSSVER=""
if [ -n "${CUDSS_DIR:-}" ] && [ -f "$CUDSS_DIR/include/cudss.h" ]; then
  a=$(sed -n 's/^#define CUDSS_VERSION_MAJOR  *\([0-9]*\).*/\1/p' "$CUDSS_DIR/include/cudss.h")
  b=$(sed -n 's/^#define CUDSS_VERSION_MINOR  *\([0-9]*\).*/\1/p' "$CUDSS_DIR/include/cudss.h")
  c=$(sed -n 's/^#define CUDSS_VERSION_PATCH  *\([0-9]*\).*/\1/p' "$CUDSS_DIR/include/cudss.h")
  [ -n "$a" ] && CUDSSVER=" $a.$b.$c"
fi

ver() { git -C "$ROOT/$1" describe --tags --always --dirty 2>/dev/null || echo "unknown"; }

# --- write ------------------------------------------------------------------

{
cat <<EOF
# Libraries linked into \`getdp.exe\`

GetDP version \`$VERSION\`, generated by \`build.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC').
Regenerate with \`scripts/gen_linked_libs.sh\`; do not edit by hand.

\`getdp.exe\` is linked with \`-static\` on the MinGW toolchain, so the compiler
runtimes and every numerical library built from source are inside the
executable. The DLLs below are the ones it still needs at run time.

## Must ship - on PATH, or beside \`getdp.exe\`

### Intel oneMKL$MKLVER - always

BLAS/LAPACK and the PARDISO direct solver, linked through \`mkl_rt.lib\`.

| DLL | Role |
|---|---|
| \`mkl_rt.2.dll\` | single dynamic-interface entry point |
| \`mkl_core.2.dll\` | core kernels |
| \`mkl_intel_thread.2.dll\` | threading layer |
| \`libiomp5md.dll\` | Intel OpenMP runtime, required by the threading layer |
| \`mkl_def.2.dll\` | baseline CPU kernels |
| \`mkl_avx2.2.dll\` | AVX2 kernels |
| \`mkl_avx512.2.dll\` | AVX-512 kernels |
| \`mkl_mc3.2.dll\` | pre-AVX2 kernels |

\`mkl_rt\` loads the other seven itself, so they are not import-table entries -
they will not show up in a dependency walker, and they are still required. The
last four are picked at run time from the host CPU: dropping one does not fail
at load, it costs performance or aborts inside MKL on a machine that needs it.
Ship all eight.
EOF

if [ -n "$PYDLL" ]; then
cat <<EOF

### CPython - this build embeds the interpreter

| DLL | Role |
|---|---|
| \`$PYDLL\` | embedded interpreter |

Built against \`${PYLIB:-python310.lib}\`. The interpreter also needs its standard
library on disk next to the DLL.
EOF
else
cat <<'EOF'

### CPython - not in this build

Built without embedded Python (`PY` was unset), so no `python*.dll` is needed.
Such a binary is fine for testing but is not the shippable configuration.
EOF
fi

if [ -n "${CUDSS_DIR:-}" ]; then
cat <<EOF

### NVIDIA cuDSS$CUDSSVER - this build enables GPU direct solve

| DLL | Role |
|---|---|
| \`cudss64_*.dll\` | cuDSS solver |
| \`cudss_mtlayer_*.dll\` | cuDSS multithreading layer |
| \`cudart64_*.dll\` | CUDA runtime |
| \`cublas64_*.dll\` | pulled in by cuDSS |
| \`cublasLt64_*.dll\` | pulled in by cuDSS |

cuDSS is called as a plain host API, so no \`nvcc\` and no CUDA Toolkit install
are needed to *build* - but \`cudart\` is linked, so its DLL is needed to *run*.
EOF
else
cat <<'EOF'

### NVIDIA cuDSS - not in this build

Built without GPU direct solve (`CUDSS_DIR` was unset), so no CUDA or cuDSS
DLLs are needed.
EOF
fi

# Real import table, when the toolchain's objdump is available. This is the
# authoritative list of *direct* imports; the MKL kernels above are loaded
# dynamically by mkl_rt and deliberately do not appear here.
OBJDUMP=$(command -v x86_64-w64-mingw32-objdump || command -v objdump || true)
if [ -n "$OBJDUMP" ] && [ -f "$EXE" ]; then
  imports=$("$OBJDUMP" -p "$EXE" 2>/dev/null | sed -n 's/^\tDLL Name: //p' | sort -u)
  if [ -n "$imports" ]; then
    echo
    echo "## Direct imports of this binary"
    echo
    echo 'Read from the built executable with `objdump -p`. System DLLs shipped'
    echo 'with Windows are listed too; only the non-system entries need shipping.'
    echo
    echo '```'
    echo "$imports"
    echo '```'
  fi
fi

cat <<EOF

## Already inside \`getdp.exe\` - nothing to ship

Statically linked, listed so it is clear what the binary contains and under
which terms it is redistributed.

| Component | Version | Licence |
|---|---|---|
| GetDP (CENOS fork) | $VERSION | GPL v2 or later (\`LICENSE.txt\`) |
| Gmsh (as \`libgmsh.a\`) | $(ver gmsh) | GPL v2 or later, with exception (\`LICENSE.txt\`) |
| PETSc | $(ver petsc) | BSD 2-clause (\`LICENSE\`) |
| MUMPS | 5.6.2 | CeCILL-C - confirm in the downloaded tarball |
| METIS | ${METIS_TAG:-v5.1.0-p12} | Apache 2.0 - confirm in the downloaded source |
| OpenBLAS | $(ver OpenBLAS) | BSD 3-clause (\`LICENSE\`) |
| Reference LAPACK | $(ver lapack) | BSD 3-clause (\`LICENSE\`) |
| MinGW-w64 runtimes | toolchain | libgcc/libstdc++/libgfortran GPL v3 + runtime exception; winpthreads MIT/zlib |

OpenBLAS and reference LAPACK are built by \`scripts/build_deps.sh\`, but the
shipped configuration links MKL for BLAS/LAPACK - they are build inputs rather
than the numerical backend of the released binary.

\`-static\` plus \`-static-libgfortran\` mean no \`libgcc_s_seh-1.dll\`,
\`libstdc++-6.dll\`, \`libgfortran-5.dll\`, \`libquadmath-0.dll\` or
\`libwinpthread-1.dll\` are needed. If any of those appear in the binary's
import table, the \`-static\` link flag was lost and the build is wrong.

## Redistributables under vendor terms

Intel oneMKL, the Intel OpenMP runtime, CPython and the NVIDIA CUDA/cuDSS DLLs
are redistributed binaries, not built here. They are covered by their own vendor
licences, and that licence text has to ship with them. Check the current terms
against the licence files in the source installs rather than against this file.
EOF
} > "$OUT"

echo "$OUT"
